[package]
name = "ruzz"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
curl = "0.4.46"
clap = {version = "4.5.20", features = ["derive"]}
regex = "1.11.0"
anyhow = "1.0.89"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.12.8"
url = "2.5.2"