[package]
name = "ruzz"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
log = "0.4.21"
curl = "0.4.46"
clap = {version = "4.5.20", features = ["derive"]}
regex = "1.11.0"
anyhow = "1.0.89"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.12.8"
url = "2.5.2"
=======
clap = { version="4.4", features = ["derive"] }
regex = "1.10"
anyhow = "1.0"
url = "2.4"
reqwest = { version = "0.11", features = ["json"]  }
tokio = { version = "1", features = ["full"]  }
serde_json = "1.0"
>>>>>>> 21b639b (Debugging reqwest to properly get the body and the headers withing one request)
